#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Tue Mar 04 13:22:03 +03 2025
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim soc_test_behav -key {Behavioral:sim_1:Functional:soc_test} -tclbatch soc_test.tcl -log simulate.log"
xsim soc_test_behav -key {Behavioral:sim_1:Functional:soc_test} -tclbatch soc_test.tcl -log simulate.log

